plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'com.tenor.android.core'
    def vMajor = 0 // range between [0,+INF)
    def vMinor = 5 // range between [0,9]
    def vPatch = 1 // range between [0,99]
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode vMajor * 1000 + vMinor * 100 + vPatch
        versionName "${vMajor}.${vMinor}.${vPatch}"
    }
    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            shrinkResources false
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    testImplementation libs.junit
    testImplementation libs.mockwebserver
    implementation libs.annotation.jvm
    implementation libs.fragment
    implementation libs.recyclerview
    implementation libs.retrofit.converter.gson
    implementation libs.glide
    compileOnly libs.play.services.ads.identifier
}