[versions]
agp = "9.2.1"
annotationJvm = "1.10.0"
fragment = "1.8.9"
recyclerview = "1.4.0"
retrofit = "3.0.0"
glide = "5.0.7"
playServicesAdsIdentifier = "18.1.0"
junit = "4.13.2"
mockwebserver = "4.12.0"

[libraries]
annotation-jvm = { module = "androidx.annotation:annotation-jvm", version.ref = "annotationJvm" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
junit = { module = "junit:junit", version.ref = "junit" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
